### ISSUE TITLE
ECONNRESET crash

### ISSUE THREAD

**Issue by creeperyang** [creeperyang/sugar-cli#22]
Sometimes `read ECONNRESET` error occurs and result to client reload fails.

**Comment by creeperyang** [comment]
The error occurs conditionally. Full message is 

``` bash
#  node@6.2.1

Error: read ECONNRESET
      at exports._errnoException (util.js:1007:11)
      at TCP.onread (net.js:563:26)
```

In fact, the error resulted from `tiny-lr` (livereload).

Seems https://github.com/livereload/LiveReload/issues/12 has a detailed discussion and 

```
this.socket.on('error', function(err) {
        return console.error(err);
});
```

can resolve the error.

So, the issue will be closed here. Maybe it's `tiny-lr`'s responsibility to resolve the bug.
